name: "Build & Deploy Page"
on:
  workflow_dispatch:
  push:
    branches:
      - $ros_distro$
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Lemvos/sphinx-pages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
        deploy: true
        source_dir: 'source'